language: node_js
node_js:
  - 8
cache: yarn

# Define global C++ compiler version
env:
  global:
    - CXX=g++-4.8
before_install:
  # Yarn defaults to an old version, make sure we
  # get an up to date version
  - npm install -g yarn@1.10.1
  - '[ "${NPM_TOKEN+x}" ] && echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > $HOME/.npmrc || echo "Skipping .npmrc creation";'

before_script:
  - cp config/ci.config.json config/project.json

# Misc Addons/Configs
dist: trusty
sudo: required
addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8

jobs:
  include:
    - stage: test
      name: Database Nodejs & Chrome Test w/ Prod Server
      script:
        - cd packages/database
        - yarn test
    - stage: test
      name: Database Node Test w/ Emulators
      before_script:
        - cp config/ci.config.json config/project.json
        - firebase setup:emulators:database
        - firebase serve --only database &
      script:
        - cd packages/database
        - yarn test:node
      env: DATABASE_EMULATOR_ADDRESS=localhost:9000
    - stage: test
      name: Database Browser Test w/ Emulators (crawler_support.test)
      before_script:
        - cp config/ci.config.json config/project.json
        - firebase setup:emulators:database
        - firebase serve --only database &
      script:
        - cd packages/database
        - karma start karma.crawler-support-test.js --single-run
      env: DATABASE_EMULATOR_ADDRESS=localhost:9000
    - stage: test
      name: Database Browser Test w/ Emulators (transaction.test)
      before_script:
        - cp config/ci.config.json config/project.json
        - firebase setup:emulators:database
        - firebase serve --only database &
      script:
        - cd packages/database
        - karma start karma.transaction-test.js --single-run
      env: DATABASE_EMULATOR_ADDRESS=localhost:9000
    - stage: test
      name: Database Browser Test w/ Emulators (all other tests)
      before_script:
        - cp config/ci.config.json config/project.json
        - firebase setup:emulators:database
        - firebase serve --only database &
      script:
        - cd packages/database
        - karma start karma.other-tests.js --single-run
      env: DATABASE_EMULATOR_ADDRESS=localhost:9000
